// DO NOT MODIFY THIS FILE'S CONTENT! THE CONTENT OF THIS FILE IS AUTOGENERATED! ONLY MODIFY THIS FILE IF YOU KNOW WHAT YOU ARE DOING!
#include "constants/excavation.h"

static const int SpriteTileTable[][16] = {
    [ITEMID_SUN_STONE] = {
      0,1,0,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_STAR_PIECE] = {
      0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,
    },
    [ITEMID_RED_SHARD] = {
      1,1,1,0,1,1,0,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_THUNDER_STONE] = {
      0,1,1,0,1,1,1,0,1,1,0,0,0,0,0,0,
    },
    [ITEMID_REVIVE] = {
      0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0,
    },
    [ITEMID_FIRE_STONE] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_SHOAL_SHELL] = {
      1,0,1,0,1,1,1,0,1,1,1,1,0,1,0,1,
    },
    [ITEMID_LEAF_STONE] = {
      0,1,0,0,1,1,1,0,1,1,1,0,0,1,0,0,
    },
    [ITEMID_SHOAL_SALT] = {
      1,0,1,0,1,1,1,1,1,1,1,1,0,0,0,0,
    },
    [ITEMID_PEARL] = {
      1,1,1,0,1,1,1,0,1,0,1,0,0,0,0,0,
    },
    [ITEMID_BLUE_SHARD] = {
      1,1,1,0,1,1,1,0,1,1,0,0,0,0,0,0,
    },
    [ITEMID_ROOT_FOSSIL] = {
      1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,0,
    },
    [ITEMID_MOON_STONE] = {
      0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,
    },
    [ITEMID_YELLOW_SHARD] = {
      1,0,1,0,1,1,1,0,1,1,1,1,0,0,0,0,
    },
    [ITEMID_BIG_PEARL] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_EVERSTONE] = {
      1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,
    },
    [ITEMID_GREEN_SHARD] = {
      1,1,1,1,1,1,1,1,1,1,0,1,0,0,0,0,
    },
    [ITEMID_CLAW_FOSSIL] = {
      1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
    },
    [ITEMID_HARD_STONE] = {
      1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
    },
    [ITEMID_MAX_REVIVE] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_WATER_STONE] = {
      1,1,1,0,1,1,1,0,1,1,0,0,0,0,0,0,
    },
    [ITEMID_NUGGET] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ITEMID_HEART_SCALE] = {
      1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_2x4] = {
      1,1,0,0,1,1,0,0,1,1,0,0,1,1,0,0,
    },
    [ID_STONE_MUSHROOM1] = {
      1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_1x4] = {
      1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,
    },
    [ID_STONE_4x2] = {
      1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_4x1] = {
      1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_3x3] = {
      1,1,1,0,1,1,1,0,1,1,1,0,0,0,0,0,
    },
    [ID_STONE_SNAKE1] = {
      1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_MUSHROOM2] = {
      0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_2x2] = {
      1,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,
    },
    [ID_STONE_SNAKE2] = {
      0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,
    },
};